# Generated by Django 5.2.16 on 2026-07-21 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('sentiment', '감정 분석'), ('summarize', '문서 요약'), ('moderate', '유해 표현 분석'), ('chain', 'Pipeline Chaining')], max_length=20)),
                ('model_name', models.CharField(max_length=200)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_execution_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', '-created_at'], name='my_gpt_aiex_feature_43d0b7_idx'), models.Index(fields=['user', '-created_at'], name='my_gpt_aiex_user_id_94c3e5_idx')],
            },
        ),
    ]
